language: cpp

before_install:
  - sudo apt-add-repository ppa:linuxjedi/ppa -y
  - sudo apt-get update -qq
  - mysql -uroot -e "grant all on *.* to 'test'@'localhost' identified by 'test';"
  - sudo cp $(pwd)/.ci/ssl.cnf /etc/mysql/conf.d/
  - sudo cp $(pwd)/tests/ssl/ca-cert.pem $(pwd)/tests/ssl/server-cert.pem $(pwd)/tests/ssl/server-key.pem /etc/mysql/
  - sudo service mysql restart
script:
  - sudo -E su ${USER} -c "sh -e \"${CI_SCRIPTS}/${CI_TARGET}.sh\""

notifications:
  irc:
    channels:
      - "chat.freenode.net#libAttachSQL"
    use_notice: true
    skip_join: true
    template:
      - "%{result}: %{repository_name}#%{build_number} (%{branch} - %{commit} : %{author}): %{build_url}"

env:
  global:
   - PROJECT_ROOT="$(pwd)"
   - CI_SCRIPTS="$PROJECT_ROOT/.ci"
   - "MYSQL_SOCK=/var/run/mysqld/mysqld.sock"
  matrix:
   - CI_TARGET=gcc-distcheck
   - CI_TARGET=gcc-ia32
   - CI_TARGET=clang
   - CI_TARGET=clang-ia32
   - CI_TARGET=clang-3.4
   - CI_TARGET=no-optional
   - CI_TARGET=valgrind
   - CI_TARGET=cppcheck
   - CI_TARGET=scanbuild
   - CI_TARGET=docs
