- job:
    name: scanbuild
    run: playbooks/scanbuild.yaml
    timeout: 7200
    nodeset:
        nodes:
            - name: xenial
              label: ubuntu-xenial

- project:
    check:
        jobs:
            - scanbuild
            - noop
