- job:
    name: base
    parent: null
    description: |
      The base job.

      All jobs ultimately inherit from this.  It runs a pre-playbook
      which copies all of the job's prepared git repos on to all of
      the nodes in the nodeset.

      It also sets a default timeout value (which may be overidden).
    pre-run:
        - playbooks/base/pre.yaml
    post-run:
        - playbooks/base/post-ssh.yaml
        - playbooks/base/post-logs.yaml
    roles:
      - zuul: openstack-infra/zuul-jobs
    timeout: 1800

- job:
    name: scanbuild
    run: playbooks/scanbuild.yaml
    timeout: 7200
    nodeset:
        nodes:
            - name: xenial
              label: ubuntu-xenial

- project:
    check:
        jobs:
            - scanbuild
            - noop
