- hosts: xenial
  name: CLang Scan Build
  any_errors_fatal: true
  tasks:
      - name: Build and run Clang ScanBuild
        shell: "{{ item }} chdir=~/src/github.com/libattachsql/libattachsql/"
        with_items:
          - autoreconf -fi
          - ./configure --enable-debug
          - scan-build --use-cc=clang --use-c++=clang --status-bugs make
        environment:
          CC="clang"
          CXX="clang++"

