- hosts: xenial
  name: CLang Scan Build
  any_errors_fatal: true
  tasks:
      - name: Ensure legacy workspace directory
        file:
            path: '{{ ansible_user_dir }}/workspace'
            state: directory
        shell:
          cmd: |
              autoreconf -fi
              ./configure --enable-debug
              scan-build --use-cc=clang --use-c++=clang --status-bugs make
          executable: /bin/bash
          chdir: '~/src/github.com/libattachsql/libattachsql/'
        environment:
          CC="clang"
          CXX="clang++"

