- hosts: xenial
  name: CLang Scan Build
  any_errors_fatal: true
  tasks:
      - name: Build and run Clang ScanBuild
        shell:
          cmd: autoreconf -fi && ./configure --enable-debug && scan-build --use-cc=clang --use-c++=clang --status-bugs make
        args:
          chdir: ~/src/github.com/libattachsql/libattachsql/
          executable: /bin/bash
        environment:
          CC="clang"
          CXX="clang++"

