- hosts: xenial
  name: CLang Scan Build
  tasks:
      - name: Ensure legacy workspace directory
        file:
            path: '{{ ansible_user_dir }}/workspace'
            state: directory
      - shell:
          cmd: |
              CC="clang"
              CXX="clang++"
              autoreconf -fi
              ./configure --enable-debug
              scan-build --use-cc=clang --use-c++=clang --status-bugs make
          executable: /bin/bash
          chdir: '~/src/github.com/libattachsql/libattachsql/'

